version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: api_service
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
      - MONGO_URI=mongodb://mongo:27017/your_db_name
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: mongo_service
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db


  telegram_bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    container_name: telegram_bot_service
    volumes:
      - .:/app
    depends_on:
      - api
      - mongo
    environment:
      - BOT_TOKEN=<your-bot-token>

volumes:
  mongo_data: