# Dockerfile.api
FROM python:3.11.7-slim

WORKDIR /app/API

COPY API/requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install gunicorn  # Install Gunicorn

COPY API /app

CMD ["gunicorn", "--bind", "0.0.0.0:5000", "run:app"]

